// js/data.js

const contentData = {
    levels: [
        { 
            id: "A1", 
            title: "Niveau A1 - Débutant", 
            description: "Alphabet, salutations, présentations et structures de base.", 
            quizQuestions: [
                { question: "Quelle lettre cyrillique correspond au son [d]?", options: ["Б", "Д", "В", "Г"], correctAnswer: 1 },
                { question: "Comment dit-on 'Merci' en russe?", options: ["Привет", "Пока", "Спасибо", "Да"], correctAnswer: 2 },
                { question: "Que signifie 'Здравствуйте'?", options: ["Salut", "Au revoir", "Excusez-moi", "Bonjour (formel)"], correctAnswer: 3 },
                { question: "Traduisez 'Non' en russe.", options: ["Да", "Нет", "Кто", "Что"], correctAnswer: 1 },
                { question: "Quelle est la question pour demander 'Qui est-ce?'?", options: ["Что это?", "Где это?", "Кто это?", "Как дела?"], correctAnswer: 2 },
                { question: "La phrase 'Меня зовут Анна' signifie:", options: ["Je suis Anna", "Je m'appelle Anna", "Tu es Anna", "Elle est Anna"], correctAnswer: 1 },
                { question: "Quelle lettre fait le son [j] comme dans 'journal'?", options: ["З", "Ж", "Х", "Ц"], correctAnswer: 1 },
                { question: "Comment saluer un ami de manière informelle?", options: ["До свидания", "Здравствуйте", "Привет", "Извините"], correctAnswer: 2 },
                { question: "Que signifie 'Пожалуйста'?", options: ["Merci et Au revoir", "Oui et Non", "S'il vous plaît / De rien", "Bonjour et Salut"], correctAnswer: 2 },
                { question: "Quelle lettre ressemble à un 'P' latin mais se prononce [r]?", options: ["П", "Ф", "Р", "С"], correctAnswer: 2 },
                { question: "Traduisez 'Oui'.", options: ["Да", "Нет", "Он", "Она"], correctAnswer: 0 },
                { question: "La lettre 'В' se prononce comme...", options: ["[b]", "[v]", "[g]", "[p]"], correctAnswer: 1 },
                { question: "Pour dire 'Au revoir' de manière formelle, on utilise:", options: ["Пока", "Привет", "До свидания", "Спасибо"], correctAnswer: 2 },
                { question: "La lettre 'У' se prononce comme...", options: ["[i]", "[a]", "[ou]", "[è]"], correctAnswer: 2 },
                { question: "Pour demander ce qu'est un objet, on dit:", options: ["Кто это?", "Что это?", "Где это?", "Когда?"], correctAnswer: 1 },
                { question: "Quelle lettre cyrillique correspond au son [f]?", options: ["Ф", "П", "Р", "Х"], correctAnswer: 0 },
                { question: "Que veut dire 'Пока'?", options: ["Bonjour", "Merci", "Salut (en partant)", "Excusez-moi"], correctAnswer: 2 },
                { question: "Comment demander 'Comment ça va?' de manière informelle?", options: ["Как вас зовут?", "Что это?", "Как дела?", "Очень приятно"], correctAnswer: 2 },
                { question: "La lettre 'Г' correspond au son:", options: ["[d]", "[v]", "[b]", "[g]"], correctAnswer: 3 },
                { question: "Comment dit-on 'Excusez-moi'?", options: ["Простите", "Извините", "Les deux sont corrects", "Спасибо"], correctAnswer: 2 },
                { question: "La lettre 'Н' se prononce comme...", options: ["h", "n", "p", "u"], correctAnswer: 1 },
                { question: "Que signifie 'Очень приятно'?", options: ["Très bien", "Enchanté", "Au revoir", "Comment ça va?"], correctAnswer: 1 },
                { question: "Quelle est la lettre pour le son [ts] comme dans 'tsar'?", options: ["Ч", "Ц", "Ш", "Щ"], correctAnswer: 1 },
                { question: "Traduisez la question 'Как тебя зовут?'", options: ["Comment ça va?", "Comment t'appelles-tu?", "Qui est-ce?", "Où es-tu?"], correctAnswer: 1 },
                { question: "La lettre 'П' se prononce...", options: ["[r]", "[p]", "[f]", "[l]"], correctAnswer: 1 },
                { question: "Quelle lettre est l'équivalent du 'S' latin?", options: ["З", "К", "С", "Х"], correctAnswer: 2 },
                { question: "La lettre 'Л' correspond au son:", options: ["[l]", "[m]", "[d]", "[i]"], correctAnswer: 0 },
                { question: "La lettre 'З' se prononce comme...", options: ["[s]", "[z]", "[j]", "[ts]"], correctAnswer: 1 },
                { question: "Que signifie le mot 'Я'?", options: ["Tu", "Il", "Je", "Nous"], correctAnswer: 2 },
                { question: "La lettre 'К' correspond au son...", options: ["[k]", "[s]", "[h]", "[g]"], correctAnswer: 0 },
                { question: "Que signifie 'Ты'?", options: ["Je", "Il", "Vous", "Tu"], correctAnswer: 3 },
                { question: "Quelle lettre fait le son 'ch' comme dans 'chat'?", options: ["Ч", "Ш", "Щ", "Х"], correctAnswer: 1 },
                { question: "Que signifie 'Он'?", options: ["Elle", "Il", "Ça", "Nous"], correctAnswer: 1 },
                { question: "La lettre 'М' se prononce comme...", options: ["[m]", "[n]", "[t]", "[p]"], correctAnswer: 0 },
                { question: "Que signifie 'Она'?", options: ["Il", "Je", "Elle", "Ils"], correctAnswer: 2 },
                { question: "La lettre 'Т' correspond au son:", options: ["[d]", "[t]", "[f]", "[r]"], correctAnswer: 1 },
                { question: "Que signifie 'Мы'?", options: ["Vous", "Ils", "Nous", "Tu"], correctAnswer: 2 },
                { question: "Quelle lettre fait le son 'tch' comme dans 'match'?", options: ["Ц", "Ч", "Ш", "Щ"], correctAnswer: 1 },
                { question: "Que signifie 'Вы'?", options: ["Vous (formel ou pluriel)", "Ils", "Nous", "Tu"], correctAnswer: 0 },
                { question: "La lettre 'Э' se prononce comme...", options: ["[ié]", "[è]", "[i]", "[o]"], correctAnswer: 1 },
                { question: "Que signifie 'Они'?", options: ["Ils/Elles", "Nous", "Vous", "Je"], correctAnswer: 0 },
                { question: "La lettre 'Ю' se prononce...", options: ["[ou]", "[iou]", "[i]", "[è]"], correctAnswer: 1 },
                { question: "Que veut dire 'Да, это я.'?", options: ["Non, c'est moi.", "Oui, c'est toi.", "Oui, c'est moi.", "Non, c'est toi."], correctAnswer: 2 },
                { question: "La lettre 'Я' se prononce...", options: ["[a]", "[ia]", "[i]", "[o]"], correctAnswer: 1 },
                { question: "Complétez la phrase : ... зовут Марк.", options: ["Я", "Ты", "Меня", "Мне"], correctAnswer: 2 },
                { question: "Quelle lettre n'a pas de son propre mais indique la mollesse de la consonne précédente?", options: ["Ъ (signe dur)", "Ь (signe mou)", "Ы", "Э"], correctAnswer: 1 },
                { question: "Que signifie 'хорошо'?", options: ["Mal", "Bien / D'accord", "Peut-être", "Merci"], correctAnswer: 1 },
                { question: "Quel est le mot russe pour 'et'?", options: ["А", "Но", "И", "Или"], correctAnswer: 2 },
                { question: "Le mot 'вода' (eau) est de genre...", options: ["Masculin", "Féminin", "Neutre"], correctAnswer: 1 },
                { question: "Comment dit-on 'frère'?", options: ["Сестра", "Мама", "Брат", "Папа"], correctAnswer: 2 },
                { question: "Traduisez 'Это мой дом'.", options: ["C'est ta maison", "C'est ma maison", "C'est sa maison", "C'est une maison"], correctAnswer: 1 },
                { question: "Le mot 'стол' (table) est de genre...", options: ["Masculin", "Féminin", "Neutre"], correctAnswer: 0 },
                { question: "Que signifie 'Где туалет?'?", options: ["Où est le bus?", "Où sont les toilettes?", "Qui est à la toilette?", "Qu'est-ce que la toilette?"], correctAnswer: 1 },
                { question: "Quel est le contraire de 'большой' (grand)?", options: ["Новый", "Маленький", "Старый", "Плохо"], correctAnswer: 1 },
                { question: "Le chiffre 'пять' correspond à :", options: ["3", "4", "5", "6"], correctAnswer: 2 },
                { question: "Comment dit-on 'Je ne comprends pas'?", options: ["Я не знаю", "Я не говорю", "Я не понимаю", "Я не хочу"], correctAnswer: 2 },
                { question: "Le mot 'окно' (fenêtre) est de genre...", options: ["Masculin", "Féminin", "Neutre"], correctAnswer: 2 },
                { question: "Que signifie 'Россия'?", options: ["Paris", "Moscou", "Russie", "France"], correctAnswer: 2 },
                { question: "Comment demander 'combien ça coûte'?", options: ["Сколько стоит?", "Что это?", "Где это?", "Почему?"], correctAnswer: 0 },
                { question: "Traduisez 'Mon nom est...'", options: ["Тебя зовут...", "Его зовут...", "Меня зовут...", "Её зовут..."], correctAnswer: 2 },
                { question: "Quelle préposition signifie 'dans' ou 'à' (lieu)?", options: ["На", "С", "В", "К"], correctAnswer: 2 },
                { question: "Que signifie 'кофе'?", options: ["Thé", "Jus", "Eau", "Café"], correctAnswer: 3 },
                { question: "Comment dit-on 'Je veux'?", options: ["Я могу", "Я люблю", "Я хочу", "Я делаю"], correctAnswer: 2 },
                { question: "Quel mot signifie 'aujourd'hui'?", options: ["Завтра", "Вчера", "Сегодня", "Сейчас"], correctAnswer: 2 }
            ], 
            vocabularyBank: [
                {ru: 'да', fr: 'oui'}, {ru: 'нет', fr: 'non'}, {ru: 'спасибо', fr: 'merci'}, {ru: 'пожалуйста', fr: 's\'il vous plaît / de rien'}, {ru: 'здравствуйте', fr: 'bonjour (formel)'}, {ru: 'привет', fr: 'salut'}, {ru: 'до свидания', fr: 'au revoir'}, {ru: 'пока', fr: 'salut (départ)'}, {ru: 'извините', fr: 'excusez-moi'}, {ru: 'я', fr: 'je'}, {ru: 'ты', fr: 'tu'}, {ru: 'он', fr: 'il'}, {ru: 'она', fr: 'elle'}, {ru: 'оно', fr: 'ça (neutre)'}, {ru: 'мы', fr: 'nous'}, {ru: 'вы', fr: 'vous'}, {ru: 'они', fr: 'ils/elles'}, {ru: 'что', fr: 'que/quoi'}, {ru: 'кто', fr: 'qui'}, {ru: 'где', fr: 'où'}, {ru: 'когда', fr: 'quand'}, {ru: 'как', fr: 'comment'}, {ru: 'почему', fr: 'pourquoi'}, {ru: 'и', fr: 'et'}, {ru: 'а', fr: 'et/mais (contraste)'}, {ru: 'но', fr: 'mais'}, {ru: 'или', fr: 'ou'}, {ru: 'дом', fr: 'maison'}, {ru: 'машина', fr: 'voiture'}, {ru: 'книга', fr: 'livre'}, {ru: 'стол', fr: 'table'}, {ru: 'стул', fr: 'chaise'}, {ru: 'окно', fr: 'fenêtre'}, {ru: 'вода', fr: 'eau'}, {ru: 'хлеб', fr: 'pain'}, {ru: 'кофе', fr: 'café'}, {ru: 'чай', fr: 'thé'}, {ru: 'хорошо', fr: 'bien/d\'accord'}, {ru: 'плохо', fr: 'mal'}, {ru: 'большой', fr: 'grand'}, {ru: 'маленький', fr: 'petit'}, {ru: 'новый', fr: 'nouveau'}, {ru: 'старый', fr: 'vieux'}, {ru: 'человек', fr: 'personne'}, {ru: 'друг', fr: 'ami'}, {ru: 'подруга', fr: 'amie'}, {ru: 'мама', fr: 'maman'}, {ru: 'папа', fr: 'papa'}, {ru: 'брат', fr: 'frère'}, {ru: 'сестра', fr: 'sœur'}, {ru: 'сын', fr: 'fils'}, {ru: 'дочь', fr: 'fille'}, {ru: 'имя', fr: 'prénom'}, {ru: 'фамилия', fr: 'nom de famille'}, {ru: 'один', fr: 'un'}, {ru: 'два', fr: 'deux'}, {ru: 'три', fr: 'trois'}, {ru: 'четыре', fr: 'quatre'}, {ru: 'пять', fr: 'cinq'}, {ru: 'шесть', fr: 'six'}, {ru: 'семь', fr: 'sept'}, {ru: 'восемь', fr: 'huit'}, {ru: 'девять', fr: 'neuf'}, {ru: 'десять', fr: 'dix'}, {ru: 'школа', fr: 'école'}, {ru: 'работа', fr: 'travail'}, {ru: 'студент', fr: 'étudiant'}, {ru: 'учитель', fr: 'professeur'}, {ru: 'врач', fr: 'médecin'}, {ru: 'город', fr: 'ville'}, {ru: 'страна', fr: 'pays'}, {ru: 'Россия', fr: 'Russie'}, {ru: 'Москва', fr: 'Moscou'}, {ru: 'говорить', fr: 'parler'}, {ru: 'знать', fr: 'savoir'}, {ru: 'понимать', fr: 'comprendre'}, {ru: 'любить', fr: 'aimer'}, {ru: 'хотеть', fr: 'vouloir'}, {ru: 'делать', fr: 'faire'}, {ru: 'жить', fr: 'vivre'}, {ru: 'работать', fr: 'travailler'}, {ru: 'читать', fr: 'lire'}, {ru: 'писать', fr: 'écrire'}, {ru: 'мочь', fr: 'pouvoir'}, {ru: 'видеть', fr: 'voir'}, {ru: 'идти', fr: 'aller (à pied)'}, {ru: 'сегодня', fr: 'aujourd\'hui'}, {ru: 'вчера', fr: 'hier'}, {ru: 'завтра', fr: 'demain'}, {ru: 'красный', fr: 'rouge'}, {ru: 'синий', fr: 'bleu'}, {ru: 'белый', fr: 'blanc'}, {ru: 'чёрный', fr: 'noir'}
            ],
            sentenceBank: [
                { ru: 'Это мой дом.', fr: 'C\'est ma maison.' },
                { ru: 'Меня зовут Иван.', fr: 'Je m\'appelle Ivan.' },
                { ru: 'Как у тебя дела?', fr: 'Comment vas-tu ?' },
                { ru: 'Я не понимаю.', fr: 'Je ne comprends pas.' },
                { ru: 'Где находится туалет?', fr: 'Où se trouvent les toilettes ?' },
                { ru: 'Сколько это стоит?', fr: 'Combien ça coûte ?' },
                { ru: 'Он говорит по-английски.', fr: 'Il parle anglais.' },
                { ru: 'Она живёт в Москве.', fr: 'Elle vit à Moscou.' }
            ]
        },
        { 
            id: "A2", 
            title: "Niveau A2 - Élémentaire", 
            description: "Cas de base (prépositionnel, accusatif), conjugaison, adjectifs et passé.", 
            quizQuestions: [
                { question: "Quel est le genre du mot 'книга' (livre)?", options: ["Masculin", "Féminin", "Neutre"], correctAnswer: 1 },
                { question: "Complétez la phrase : Я ... по-русски.", options: ["говорит", "говорим", "говорю", "говорят"], correctAnswer: 2 },
                { question: "Choisissez la forme correcte au prépositionnel : Она живёт в ...", options: ["Лондон", "Лондона", "Лондоне"], correctAnswer: 2 },
                { question: "Quel pronom possessif utiliser avec 'дом' (maison, masc.)?", options: ["моя", "моё", "мой"], correctAnswer: 2 },
                { question: "Traduisez : 'Je vois la table.' (стол - m. inanimé)", options: ["Я вижу стол", "Я вижу стола", "Я вижу столе"], correctAnswer: 0 },
                { question: "Le mot 'окно' (fenêtre) est de genre :", options: ["Masculin", "Féminin", "Neutre"], correctAnswer: 2 },
                { question: "Complétez : Они ... чай.", options: ["любит", "любят", "любишь", "люблю"], correctAnswer: 1 },
                { question: "Le cas prépositionnel est utilisé pour indiquer...", options: ["la possession", "l'objet direct", "le lieu ('où?')"], correctAnswer: 2 },
                { question: "'Эта' est la forme féminine de quel pronom démonstratif?", options: ["Мой", "Этот", "Наш"], correctAnswer: 1 },
                { question: "Quelle est la terminaison correcte ? 'Ты чита...?'", options: ["-ю", "-ет", "-ешь", "-ем"], correctAnswer: 2 },
                { question: "Traduisez 'Elle aime le café.' (кофе - m.).", options: ["Она любит кофе", "Она любит кофю", "Она любит кофее"], correctAnswer: 0 },
                { question: "Le mot 'студент' (étudiant) est de genre:", options: ["Masculin", "Féminin", "Neutre"], correctAnswer: 0 },
                { question: "Complétez : Мы ... в России.", options: ["живёшь", "живёт", "живём", "живут"], correctAnswer: 2 },
                { question: "Quelle est la forme correcte ? 'Он на ...' (работа - travail, f.)", options: ["работу", "работе", "работа"], correctAnswer: 1 },
                { question: "Comment dit-on 'Vous voulez' (formel)?", options: ["Ты хочешь", "Они хотят", "Вы хотите"], correctAnswer: 2 },
                { question: "Le mot 'море' (mer) est de genre:", options: ["Masculin", "Féminin", "Neutre"], correctAnswer: 2 },
                { question: "Complétez : Вы ...?", options: ["понимаю", "понимаете", "понимаешь"], correctAnswer: 1 },
                { question: "Traduisez : 'Je lis un journal' (газета - f.)", options: ["Я читаю газета", "Я читаю газете", "Я читаю газету"], correctAnswer: 2 },
                { question: "Quel pronom utiliser pour 'ma soeur' (моя сестра)?", options: ["Он", "Она", "Оно"], correctAnswer: 1 },
                { question: "Le cas accusatif est utilisé pour indiquer...", options: ["le lieu", "l'objet direct", "l'instrument"], correctAnswer: 1 },
                { question: "Complétez : Она ... телевизор.", options: ["смотрю", "смотрят", "смотрит"], correctAnswer: 2 },
                { question: "Le mot 'учитель' (professeur) est de genre:", options: ["Masculin", "Féminin", "Neutre"], correctAnswer: 0 },
                { question: "Forme correcte au prépositionnel: 'в ... (школа, f.)'", options: ["школу", "школе", "школы"], correctAnswer: 1 },
                { question: "Complétez : Я не ... где он.", options: ["знаю", "знает", "знают"], correctAnswer: 0 },
                { question: "Traduisez 'Il achète une voiture' (машина - f.)", options: ["Он покупает машина", "Он покупает машину", "Он покупает машине"], correctAnswer: 1 },
                { question: "Quel pronom possessif pour 'lettre' (письмо, n.)?", options: ["мой", "моя", "моё"], correctAnswer: 2 },
                { question: "Complétez : Ты ... музыку?", options: ["любишь", "любит", "люблю"], correctAnswer: 0 },
                { question: "Le mot 'имя' (nom) est de genre:", options: ["Masculin", "Féminin", "Neutre"], correctAnswer: 2 },
                { question: "Forme correcte à l'accusatif : 'Я люблю ... (Россия, f.)'", options: ["Россия", "России", "Россию"], correctAnswer: 2 },
                { question: "Complétez : Он ... в университете.", options: ["учится", "учусь", "учатся"], correctAnswer: 0 },
                { question: "Quel est le genre de 'папа' (papa)?", options: ["Masculin (grammaticalement)", "Féminin (terminaison)", "Neutre"], correctAnswer: 0 },
                { question: "Traduisez 'Nous vivons dans une grande maison' (дом - m.)", options: ["Мы живём в большой дом", "Мы живём в большом доме", "Мы живём в большим домом"], correctAnswer: 1 },
                { question: "Complétez : Я ... суп.", options: ["ешь", "ест", "ем"], correctAnswer: 2 },
                { question: "Forme correcte à l'accusatif : 'Я вижу ... (брат, m. animé)'", options: ["брат", "брата", "брату"], correctAnswer: 1 },
                { question: "Le mot 'дверь' (porte) est de genre:", options: ["Masculin", "Féminin", "Neutre"], correctAnswer: 1 },
                { question: "Complétez : Вы ... по-английски?", options: ["говорите", "говоришь", "говорят"], correctAnswer: 0 },
                { question: "Traduisez : 'Ils étudient la langue russe' (русский язык - m.)", options: ["Они изучают русский язык", "Они изучают русского языка", "Они изучают русском языке"], correctAnswer: 0 },
                { question: "Le mot 'время' (temps) est de genre:", options: ["Masculin", "Féminin", "Neutre"], correctAnswer: 2 },
                { question: "Forme correcte au prépositionnel : 'на ... (стол, m.)'", options: ["стол", "стола", "столе"], correctAnswer: 2 },
                { question: "Complétez : Я ... домой.", options: ["идёт", "иду", "идёшь"], correctAnswer: 1 },
                { question: "Traduisez : 'Je connais cette fille' (девочка - f.)", options: ["Я знаю эта девочка", "Я знаю этой девочке", "Я знаю эту девочку"], correctAnswer: 2 },
                { question: "Le mot 'день' (jour) est de genre:", options: ["Masculin", "Féminin", "Neutre"], correctAnswer: 0 },
                { question: "Complétez : Он ... на гитаре.", options: ["играю", "играет", "играют"], correctAnswer: 1 },
                { question: "Forme correcte au prépositionnel : 'о ... (море, n.)'", options: ["море", "моря", "море"], correctAnswer: 0 },
                { question: "Traduisez : 'Elle écoute la radio' (радио - indéclinable)", options: ["Она слушает радио", "Она слушает радию", "Она слушает радиом"], correctAnswer: 0 },
                { question: "Le mot 'ночь' (nuit) est de genre:", options: ["Masculin", "Féminin", "Neutre"], correctAnswer: 1 },
                { question: "Complétez : Мы ... фильм.", options: ["смотрим", "смотрит", "смотрите"], correctAnswer: 0 },
                { question: "Forme correcte à l'accusatif : 'Я пью ... (молоко, n.)'", options: ["молоко", "молока", "молоку"], correctAnswer: 0 },
                { question: "Quel pronom possessif pour 'amie' (подруга, f.)?", options: ["мой", "моя", "моё"], correctAnswer: 1 },
                { question: "Complétez : Ты ... в магазине?", options: ["работаешь", "работает", "работаю"], correctAnswer: 0 },
                { question: "Mettez au passé (féminin) : 'Она ... сок.'", options: ["пил", "пила", "пило", "пили"], correctAnswer: 1 },
                { question: "Pour indiquer la destination (accusatif), on demande :", options: ["Где?", "Куда?", "Откуда?"], correctAnswer: 1 },
                { question: "Choisissez la forme correcte de l'adjectif : 'Это ... книга.' (intéressant)", options: ["интересный", "интересная", "интересное"], correctAnswer: 1 },
                { question: "Mettez au passé (pluriel) : 'Они ... в парке.'", options: ["гулял", "гуляла", "гуляли"], correctAnswer: 2 },
                { question: "Traduisez 'leur maison' (дом - m.).", options: ["Их дом", "Им дом", "Ихний дом"], correctAnswer: 0 },
                { question: "Comment dire 'notre voiture' (машина - f.)?", options: ["Наш машина", "Наше машина", "Наша машина"], correctAnswer: 2 },
                { question: "Choisissez la forme correcte : 'Он идёт ...' (au travail)", options: ["на работе", "на работу", "на работы"], correctAnswer: 1 },
                { question: "Le mot 'деньги' (argent) est...", options: ["Toujours au singulier", "Toujours au pluriel", "Masculin singulier"], correctAnswer: 1 },
                { question: "Mettez au passé (masculin) : 'Он ... письмо.'", options: ["писал", "писала", "писали"], correctAnswer: 0 },
                { question: "Quelle est la forme correcte ? 'Я говорю о ...' (mon frère)", options: ["мой брат", "моём брате", "моего брата"], correctAnswer: 1 },
                { question: "Traduisez 'J'aime ma ville' (город - m.).", options: ["Я люблю мой город", "Я люблю моего города", "Я люблю моим городом"], correctAnswer: 0 },
                { question: "Le mot 'родители' (parents) est...", options: ["Toujours au pluriel", "Toujours au singulier", "Féminin singulier"], correctAnswer: 0 },
                { question: "Complétez : 'Она ... из Франции.' (Elle est de France)", options: ["в", "из", "на"], correctAnswer: 1 },
                { question: "Quelle est la question pour 'Откуда ты?'?", options: ["Où es-tu?", "Où vas-tu?", "D'où viens-tu?"], correctAnswer: 2 },
                { question: "L'adjectif doit s'accorder avec le nom en...", options: ["Genre et nombre seulement", "Genre, nombre et cas", "Cas seulement"], correctAnswer: 1 }
            ], 
            vocabularyBank: [
                {ru: 'утро', fr: 'matin'}, {ru: 'день', fr: 'jour/journée'}, {ru: 'вечер', fr: 'soir'}, {ru: 'ночь', fr: 'nuit'}, {ru: 'неделя', fr: 'semaine'}, {ru: 'месяц', fr: 'mois'}, {ru: 'год', fr: 'année'}, {ru: 'понедельник', fr: 'lundi'}, {ru: 'вторник', fr: 'mardi'}, {ru: 'среда', fr: 'mercredi'}, {ru: 'четверг', fr: 'jeudi'}, {ru: 'пятница', fr: 'vendredi'}, {ru: 'суббота', fr: 'samedi'}, {ru: 'воскресенье', fr: 'dimanche'}, {ru: 'погода', fr: 'météo'}, {ru: 'дождь', fr: 'pluie'}, {ru: 'снег', fr: 'neige'}, {ru: 'солнце', fr: 'soleil'}, {ru: 'ветер', fr: 'vent'}, {ru: 'деньги', fr: 'argent'}, {ru: 'магазин', fr: 'magasin'}, {ru: 'рынок', fr: 'marché'}, {ru: 'ресторан', fr: 'restaurant'}, {ru: 'кафе', fr: 'café'}, {ru: 'еда', fr: 'nourriture'}, {ru: 'завтрак', fr: 'petit-déjeuner'}, {ru: 'обед', fr: 'déjeuner'}, {ru: 'ужин', fr: 'dîner'}, {ru: 'фрукт', fr: 'fruit'}, {ru: 'овощ', fr: 'légume'}, {ru: 'мясо', fr: 'viande'}, {ru: 'рыба', fr: 'poisson'}, {ru: 'курица', fr: 'poulet'}, {ru: 'сыр', fr: 'fromage'}, {ru: 'молоко', fr: 'lait'}, {ru: 'сок', fr: 'jus'}, {ru: 'купить', fr: 'acheter'}, {ru: 'платить', fr: 'payer'}, {ru: 'смотреть', fr: 'regarder'}, {ru: 'слушать', fr: 'écouter'}, {ru: 'слышать', fr: 'entendre'}, {ru: 'думать', fr: 'penser'}, {ru: 'отдыхать', fr: 'se reposer'}, {ru: 'гулять', fr: 'se promener'}, {ru: 'играть', fr: 'jouer'}, {ru: 'ехать', fr: 'aller (en transport)'}, {ru: 'красивый', fr: 'beau'}, {ru: 'интересный', fr: 'intéressant'}, {ru: 'скучный', fr: 'ennuyeux'}, {ru: 'вкусный', fr: 'délicieux'}, {ru: 'потому что', fr: 'parce que'}, {ru: 'поэтому', fr: 'c\'est pourquoi'}, {ru: 'улица', fr: 'rue'}, {ru: 'площадь', fr: 'place'}, {ru: 'язык', fr: 'langue'}, {ru: 'помогать', fr: 'aider'}, {ru: 'вопрос', fr: 'question'}, {ru: 'ответ', fr: 'réponse'}, {ru: 'всегда', fr: 'toujours'}, {ru: 'никогда', fr: 'jamais'}, {ru: 'часто', fr: 'souvent'}, {ru: 'редко', fr: 'rarement'}, {ru: 'иногда', fr: 'parfois'}, {ru: 'быстро', fr: 'vite'}, {ru: 'медленно', fr: 'lentement'}, {ru: 'квартира', fr: 'appartement'}, {ru: 'комната', fr: 'chambre/pièce'}, {ru: 'кухня', fr: 'cuisine'}, {ru: 'ванная', fr: 'salle de bain'}, {ru: 'туалет', fr: 'toilettes'}, {ru: 'дверь', fr: 'porte'}, {ru: 'семья', fr: 'famille'}, {ru: 'родители', fr: 'parents'}, {ru: 'дети', fr: 'enfants'}, {ru: 'муж', fr: 'mari'}, {ru: 'жена', fr: 'femme'}, {ru: 'одежда', fr: 'vêtements'}, {ru: 'рубашка', fr: 'chemise'}, {ru: 'платье', fr: 'robe'}, {ru: 'стоить', fr: 'coûter'}, {ru: 'дорогой', fr: 'cher'}, {ru: 'дешёвый', fr: 'bon marché'}, {ru: 'тёплый', fr: 'chaud'}, {ru: 'холодный', fr: 'froid'}, {ru: 'наш', fr: 'notre'}, {ru: 'ваш', fr: 'votre'}, {ru: 'их', fr: 'leur'}, {ru: 'этот', fr: 'ce/cet'}, {ru: 'тот', fr: 'ce/celui-là'}
            ],
            sentenceBank: [
                { ru: 'Вчера я читал интересную книгу.', fr: 'Hier, j\'ai lu un livre intéressant.' },
                { ru: 'Она купила новую машину.', fr: 'Elle a acheté une nouvelle voiture.' },
                { ru: 'Мы живём в большом городе.', fr: 'Nous vivons dans une grande ville.' },
                { ru: 'Ты любишь русскую музыку?', fr: 'Aimes-tu la musique russe ?' },
                { ru: 'Они пошли в ресторан вечером.', fr: 'Ils sont allés au restaurant le soir.' },
                { ru: 'Я хочу выпить чашку кофе.', fr: 'Je veux boire une tasse de café.' },
                { ru: 'Мой брат работает в школе.', fr: 'Mon frère travaille à l\'école.' },
                { ru: 'Я никогда не был в России.', fr: 'Je n\'ai jamais été en Russie.' }
            ]
        },
        { 
            id: "B1", 
            title: "Niveau B1 - Intermédiaire", 
            description: "Aspects des verbes, cas datif et génitif, verbes de mouvement (base).", 
            quizQuestions: [
                { question: "Choisissez la forme correcte au passé : Анна ... письмо.", options: ["писал", "писало", "писала"], correctAnswer: 2 },
                { question: "Pour une action répétée ou habituelle dans le passé, on utilise l'aspect...", options: ["Perfectif", "Imperfectif"], correctAnswer: 1 },
                { question: "Complétez avec le Génitif (négation) : У меня нет ...", options: ["машина", "машину", "машины"], correctAnswer: 2 },
                { question: "Comment dire 'Je vais lire' (processus futur)?", options: ["Я прочитаю", "Я буду читать", "Я читал"], correctAnswer: 1 },
                { question: "Quel aspect utiliser pour dire 'Hier, j'ai lu le livre (en entier)'?", options: ["Perfectif (прочитал)", "Imperfectif (читал)"], correctAnswer: 0 },
                { question: "Mettez au Datif : Я даю подарок ... (брат).", options: ["брат", "брату", "брата"], correctAnswer: 1 },
                { question: "Traduisez 'Ils ont travaillé'.", options: ["Они работал", "Они работали", "Они работало"], correctAnswer: 1 },
                { question: "Négation avec le Génitif : 'Здесь нет ...' (ресторан)", options: ["ресторан", "ресторана", "ресторане"], correctAnswer: 1 },
                { question: "La phrase 'Мне нравится фильм' utilise quel cas pour 'Мне'?", options: ["Accusatif", "Génitif", "Datif"], correctAnswer: 2 },
                { question: "Quelle est la différence entre 'делать' et 'сделать'?", options: ["Aucune", "Présent / Passé", "Imperfectif / Perfectif"], correctAnswer: 2 },
                { question: "Complétez : Вчера мы ... в кино.", options: ["ходили", "идём", "пойдём"], correctAnswer: 0 },
                { question: "Pour dire 'J'ai donné le livre à ma soeur' (сестра), on dit:", options: ["... сестре", "... сестру", "... сестры"], correctAnswer: 0 },
                { question: "Quel verbe signifie 'avoir regardé' (action unique et terminée)?", options: ["смотреть", "посмотреть"], correctAnswer: 1 },
                { question: "Comment dire 'Elle n'avait pas de temps' (время)?", options: ["У неё не было время", "У неё не было времени"], correctAnswer: 1 },
                { question: "Pour dire 'Demain je ferai mes devoirs (et je les finirai)', on utilise:", options: ["Я буду делать", "Я сделаю", "Я делал"], correctAnswer: 1 },
                { question: "Forme correcte au passé : Оно ... на столе.", options: ["лежал", "лежала", "лежало"], correctAnswer: 2 },
                { question: "Pour dire 'J'appelle mon ami' (друг), on dit : Я звоню...", options: ["друг", "друга", "другу"], correctAnswer: 2 },
                { question: "Génitif pluriel de 'студент' : 'Пять ...'", options: ["студенты", "студентов", "студентам"], correctAnswer: 1 },
                { question: "Futur du verbe 'быть' (être) à la 3e personne du pluriel : Они ...", options: ["будет", "будем", "будут"], correctAnswer: 2 },
                { question: "Pour dire 'Il a 30 ans', on dit :", options: ["Он 30 лет", "Его 30 лет", "Ему 30 лет"], correctAnswer: 2 },
                { question: "Génitif de 'вода' (eau) : 'Стакан ...'", options: ["вода", "воду", "воды"], correctAnswer: 2 },
                { question: "'J'ai regardé le film et je l'ai aimé'. Le verbe 'regarder' doit être:", options: ["Imperfectif (смотрел)", "Perfectif (посмотрел)"], correctAnswer: 1 },
                { question: "Datif de 'Анна' : 'Помоги ...'", options: ["Анна", "Анны", "Анне"], correctAnswer: 2 },
                { question: "Forme correcte au passé : Мы ...", options: ["был", "была", "были"], correctAnswer: 2 },
                { question: "Génitif de 'отец' (père) : 'Это машина моего ...'", options: ["отец", "отца", "отцу"], correctAnswer: 1 },
                { question: "Pour dire 'Il faut aider les parents' (родители), on dit 'Надо помогать...'", options: ["родители", "родителей", "родителям"], correctAnswer: 2 },
                { question: "Futur composé de 'работать' : Я ...", options: ["буду работать", "поработаю", "работал"], correctAnswer: 0 },
                { question: "'Hier, j'ai vu Ivan.'", options: ["Вчера я видел Ивана.", "Вчера я смотрел Ивана."], correctAnswer: 0 },
                { question: "Génitif pluriel de 'книга' : 'Много ...'", options: ["книг", "книги", "книгам"], correctAnswer: 0 },
                { question: "'Soudain, il a ouvert la porte.'", options: ["Он открывал дверь.", "Он открыл дверь."], correctAnswer: 1 },
                { question: "Datif de 'я' (je) : '... холодно.'", options: ["Меня", "Мне", "Мной"], correctAnswer: 1 },
                { question: "Passé du verbe 'мочь' (pouvoir), masculin : 'Он ...'", options: ["мог", "может", "сможет"], correctAnswer: 0 },
                { question: "Génitif après la préposition 'у' (chez) : 'Я был у ...'", options: ["врач", "врача", "врачу"], correctAnswer: 1 },
                { question: "Pour dire 'J'achèterai ce livre demain (c'est décidé)', on dit 'Завтра я ... эту книгу.'", options: ["буду покупать", "куплю"], correctAnswer: 1 },
                { question: "Datif pluriel de 'дети' (enfants) : 'Подарки ...'", options: ["дети", "детей", "детям"], correctAnswer: 2 },
                { question: "Passé, féminin, de 'идти' (aller) : 'Она ... в школу.'", options: ["шёл", "шла", "шли"], correctAnswer: 1 },
                { question: "Génitif après 'без' (sans) : 'Кофе без ...'", options: ["сахар", "сахара", "сахару"], correctAnswer: 1 },
                { question: "Il a lu tout le livre en une soirée.", options: ["Он читал всю книгу...", "Он прочитал всю книгу..."], correctAnswer: 1 },
                { question: "Datif de 'ты' (tu) : 'Я ... верю.'", options: ["тебя", "тебе", "тобой"], correctAnswer: 1 },
                { question: "Passé, neutre, de 'расти' (grandir) : 'Дерево ...'", options: ["рос", "росла", "росло"], correctAnswer: 2 },
                { question: "Génitif après un chiffre (2, 3, 4) : 'Два ...'", options: ["студент", "студента", "студентов"], correctAnswer: 1 },
                { question: "Je t'appellerai (action unique future).", options: ["Я буду тебе звонить.", "Я тебе позвоню."], correctAnswer: 1 },
                { question: "Datif après 'к' (vers) : 'Иди к ...'", options: ["доска", "доски", "доске"], correctAnswer: 2 },
                { question: "Passé du verbe 'хотеть' (vouloir), pluriel : 'Они ...'", options: ["хотел", "хотела", "хотели"], correctAnswer: 2 },
                { question: "Génitif de 'Россия' : 'Столица ...'", options: ["Россия", "России", "Россию"], correctAnswer: 1 },
                { question: "J'ai pris le livre (action terminée).", options: ["Я брал книгу.", "Я взял книгу."], correctAnswer: 1 },
                { question: "Pour dire 'Grâce à toi', on dit 'Благодаря ...'", options: ["тебя", "тебе", "тобой"], correctAnswer: 1 },
                { question: "Passé du verbe 'нести' (porter), masculin : 'Он ... сумку.'", options: ["нёс", "несла", "несли"], correctAnswer: 0 },
                { question: "Génitif après 'около' (près de) : 'около ...'", options: ["дом", "дома", "дому"], correctAnswer: 1 },
                { question: "Quel est le comparatif de 'хороший' (bon)?", options: ["Более хороший", "Лучше", "Хорошее"], correctAnswer: 1 },
                { question: "Complétez : 'Моя сестра ... меня.' (plus jeune)", options: ["младше", "моложе", "младшая"], correctAnswer: 0 },
                { question: "Le verbe 'ходить' signifie 'aller à pied...'", options: ["dans une seule direction, une fois", "habituellement, dans plusieurs directions", "en transport"], correctAnswer: 1 },
                { question: "Choisissez le verbe correct : 'Каждый день я ... на работу пешком.'", options: ["иду", "хожу", "еду"], correctAnswer: 1 },
                { question: "Le superlatif de 'интересный' est :", options: ["Интереснее", "Самый интересный", "Очень интересный"], correctAnswer: 1 },
                { question: "Mettez à l'instrumental : 'Я пишу ...' (un stylo)", options: ["ручка", "ручку", "ручкой"], correctAnswer: 2 },
                { question: "Le verbe 'ездить' signifie 'aller en transport...'", options: ["une seule fois, maintenant", "de manière répétée", "à pied"], correctAnswer: 1 },
                { question: "Choisissez le verbe correct : 'Завтра мы ... в Петербург.'", options: ["ездим", "едем", "ходим"], correctAnswer: 1 },
                { question: "Quel est le comparatif de 'плохой' (mauvais)?", options: ["Плохее", "Хуже", "Более плохой"], correctAnswer: 1 },
                { question: "Complétez : 'Он интересуется ...' (histoire)", options: ["история", "историю", "историей"], correctAnswer: 2 },
                { question: "Traduisez 'travailler comme ingénieur'.", options: ["работать инженер", "работать инженера", "работать инженером"], correctAnswer: 2 },
                { question: "Le mot 'который' (qui, que) doit s'accorder avec...", options: ["le nom qu'il remplace (antécédent)", "le verbe de la proposition principale", "toujours être au nominatif"], correctAnswer: 0 },
                { question: "Complétez : 'Вот книга, ... я читаю.'", options: ["которая", "которую", "которой"], correctAnswer: 1 },
                { question: "Génitif pluriel de 'год' : 'Пять ...'", options: ["год", "года", "лет"], correctAnswer: 2 },
                { question: "Complétez : 'Мне нужно ...' (ton aide)", options: ["твоя помощь", "твоей помощи", "твою помощь"], correctAnswer: 0 },
                { question: "Comment dire 'Il est devenu médecin'?", options: ["Он стал врач", "Он стал врачом", "Он стал врача"], correctAnswer: 1 }
            ], 
            vocabularyBank: [
                {ru: 'путешествовать', fr: 'voyager'}, {ru: 'отдыхать', fr: 'se reposer'}, {ru: 'билет', fr: 'billet'}, {ru: 'аэропорт', fr: 'aéroport'}, {ru: 'вокзал', fr: 'gare'}, {ru: 'поезд', fr: 'train'}, {ru: 'самолёт', fr: 'avion'}, {ru: 'гостиница', fr: 'hôtel'}, {ru: 'номер', fr: 'chambre (hôtel)/numéro'}, {ru: 'паспорт', fr: 'passeport'}, {ru: 'виза', fr: 'visa'}, {ru: 'чемодан', fr: 'valise'}, {ru: 'профессия', fr: 'profession'}, {ru: 'инженер', fr: 'ingénieur'}, {ru: 'менеджер', fr: 'manager'}, {ru: 'программист', fr: 'programmeur'}, {ru: 'дизайнер', fr: 'designer'}, {ru: 'официант', fr: 'serveur'}, {ru: 'продавец', fr: 'vendeur'}, {ru: 'компания', fr: 'entreprise'}, {ru: 'зарплата', fr: 'salaire'}, {ru: 'опыт', fr: 'expérience'}, {ru: 'встреча', fr: 'réunion/rencontre'}, {ru: 'звонить/позвонить', fr: 'appeler (téléphone)'}, {ru: 'отвечать/ответить', fr: 'répondre'}, {ru: 'спрашивать/спросить', fr: 'demander (info)'}, {ru: 'просить/попросить', fr: 'demander (requête)'}, {ru: 'показывать/показать', fr: 'montrer'}, {ru: 'рассказывать/рассказать', fr: 'raconter'}, {ru: 'объяснять/объяснить', fr: 'expliquer'}, {ru: 'советовать/посоветовать', fr: 'conseiller'}, {ru: 'предлагать/предложить', fr: 'proposer'}, {ru: 'решать/решить', fr: 'décider/résoudre'}, {ru: 'выбирать/выбрать', fr: 'choisir'}, {ru: 'начинать/начать', fr: 'commencer'}, {ru: 'заканчивать/закончить', fr: 'terminer'}, {ru: 'продолжать/продолжить', fr: 'continuer'}, {ru: 'забывать/забыть', fr: 'oublier'}, {ru: 'помнить', fr: 'se souvenir'}, {ru: 'искать/найти', fr: 'chercher/trouver'}, {ru: 'терять/потерять', fr: 'perdre'}, {ru: 'ждать/подождать', fr: 'attendre'}, {ru: 'давать/дать', fr: 'donner'}, {ru: 'брать/взять', fr: 'prendre'}, {ru: 'покупать/купить', fr: 'acheter'}, {ru: 'трудный', fr: 'difficile'}, {ru: 'лёгкий', fr: 'facile'}, {ru: 'важный', fr: 'important'}, {ru: 'нужный', fr: 'nécessaire'}, {ru: 'свободный', fr: 'libre'}, {ru: 'занятой', fr: 'occupé'}, {ru: 'больной', fr: 'malade'}, {ru: 'здоровый', fr: 'en bonne santé'}, {ru: 'голодный', fr: 'affamé'}, {ru: 'уставший', fr: 'fatigué'}, {ru: 'довольный', fr: 'content/satisfait'}, {ru: 'грустный', fr: 'triste'}, {ru: 'весёлый', fr: 'joyeux'}, {ru: 'серьёзный', fr: 'sérieux'}, {ru: 'обувь', fr: 'chaussures'}, {ru: 'подарок', fr: 'cadeau'}, {ru: 'праздник', fr: 'fête'}, {ru: 'день рождения', fr: 'anniversaire'}, {ru: 'приглашать/пригласить', fr: 'inviter'}, {ru: 'встречать/встретить', fr: 'rencontrer/accueillir'}, {ru: 'надеяться', fr: 'espérer'}, {ru: 'обещать', fr: 'promettre'}, {ru: 'смеяться', fr: 'rire'}, {ru: 'плакать', fr: 'pleurer'}, {ru: 'петь/спеть', fr: 'chanter'}, {ru: 'танцевать', fr: 'danser'}, {ru: 'рисовать/нарисовать', fr: 'dessiner'}, {ru: 'открывать/открыть', fr: 'ouvrir'}, {ru: 'закрывать/закрыть', fr: 'fermer'}, {ru: 'помощь', fr: 'aide'}, {ru: 'мнение', fr: 'opinion'}, {ru: 'цель', fr: 'but'}, {ru: 'будущее', fr: 'futur'}, {ru: 'прошлое', fr: 'passé'}, {ru: 'настоящее', fr: 'présent'}, {ru: 'лучше', fr: 'mieux/meilleur'}, {ru: 'хуже', fr: 'pire/plus mal'}, {ru: 'больше', fr: 'plus'}, {ru: 'меньше', fr: 'moins'}, {ru: 'раньше', fr: 'plus tôt / avant'}, {ru: 'позже', fr: 'plus tard'}, {ru: 'конечно', fr: 'bien sûr'}, {ru: 'может быть', fr: 'peut-être'}
            ],
            sentenceBank: [
                { ru: 'Если у меня будет время, я тебе позвоню.', fr: 'Si j\'ai le temps, je t\'appellerai.' },
                { ru: 'Ей нужно помочь родителям.', fr: 'Elle doit aider ses parents.' },
                { ru: 'У меня нет его номера телефона.', fr: 'Je n\'ai pas son numéro de téléphone.' },
                { ru: 'Он подарил своей сестре цветы.', fr: 'Il a offert des fleurs à sa sœur.' },
                { ru: 'Каждый день я хожу на работу пешком.', fr: 'Chaque jour, je vais au travail à pied.' },
                { ru: 'Когда ты закончишь работать?', fr: 'Quand finiras-tu de travailler ?' },
                { ru: 'Я думаю, что это очень хорошая идея.', fr: 'Je pense que c\'est une très bonne idée.' },
                { ru: 'Мы уже купили билеты в театр.', fr: 'Nous avons déjà acheté les billets pour le théâtre.' }
            ]
        },
        { 
            id: "B2", 
            title: "Niveau B2 - Intermédiaire Supérieur", 
            description: "Verbes de mouvement avec préfixes, participes, gérondifs et cas instrumental.", 
            quizQuestions: [
                { question: "Quel verbe signifie 'arriver en voiture' (résultat)?", options: ["прийти", "уйти", "приехать", "уехать"], correctAnswer: 2 },
                { question: "Complétez avec l'instrumental : Я интересуюсь ... (la musique).", options: ["музыка", "музыку", "музыкой"], correctAnswer: 2 },
                { question: "Comment traduire 'le livre écrit par Tolstoï'?", options: ["книга, пишущая Толстым", "книга, написанная Толстым", "книга, которую написал Толстой"], correctAnswer: 1 },
                { question: "'Il est entré dans la pièce.' se dit 'Он вошёл в комнату.' Quel est le verbe de mouvement de base?", options: ["ехать", "идти", "носить"], correctAnswer: 1 },
                { question: "Mettez à l'instrumental : Он хочет стать ... (un bon docteur).", options: ["хороший доктор", "хорошего доктора", "хорошим доктором"], correctAnswer: 2 },
                { question: "Le participe passif passé 'сделанный' signifie :", options: ["qui fait", "qui a fait", "qui est fait"], correctAnswer: 2 },
                { question: "Pour dire 'sortir de la maison (à pied)', on utilise le verbe:", options: ["войти", "выйти", "дойти"], correctAnswer: 1 },
                { question: "Traduisez 'avec de nouveaux amis' (новые друзья).", options: ["с новые друзья", "с новыми друзьями", "с новых другов"], correctAnswer: 1 },
                { question: "Que signifie 'девушка, читающая книгу'?", options: ["La fille qui a lu le livre", "Le livre que la fille lit", "La fille en train de lire un livre"], correctAnswer: 2 },
                { question: "Quel préfixe signifie une action d'arrivée?", options: ["у-", "вы-", "при-"], correctAnswer: 2 },
                { question: "Le cas instrumental répond souvent à la question:", options: ["Où?", "Avec quoi? / Par qui?", "Pour qui?"], correctAnswer: 1 },
                { question: "Le participe actif présent 'работающий' vient du verbe...", options: ["работать (imperfectif)", "поработать (perfectif)"], correctAnswer: 0 },
                { question: "Il est parti (en transport) de la ville. 'Он ... из города.'", options: ["приехал", "уехал", "доехал"], correctAnswer: 1 },
                { question: "Je suis fier de mon fils (сын). 'Я горжусь ...'", options: ["сын", "сына", "сыном"], correctAnswer: 2 },
                { question: "'Задача, решённая студентом' signifie:", options: ["L'étudiant qui résout le problème", "Le problème résolu par l'étudiant"], correctAnswer: 1 },
                { question: "Pour 'traverser la rue (à pied)', on dit...", options: ["войти в улицу", "перейти улицу", "уйти с улицы"], correctAnswer: 1 },
                { question: "Instrumental de 'ночь' (nuit) : 'работать ...'", options: ["ночь", "ночью", "ночи"], correctAnswer: 1 },
                { question: "Le participe actif passé 'купивший' signifie...", options: ["qui achète", "qui a été acheté", "qui a acheté"], correctAnswer: 2 },
                { question: "Pour 'monter au 5ème étage', on dit '... на пятый этаж'", options: ["подняться", "спуститься", "войти"], correctAnswer: 0 },
                { question: "Complétez : 'Он был ... (un bon étudiant)'", options: ["хороший студент", "хорошим студентом", "хорошего студента"], correctAnswer: 1 },
                { question: "'Закрытая дверь' signifie:", options: ["la porte qui ferme", "la porte fermée", "la porte qui a fermé"], correctAnswer: 1 },
                { question: "Pour 'faire le tour de la ville (à pied)', on dit...", options: ["обойти город", "пройти город", "уйти из города"], correctAnswer: 0 },
                { question: "Instrumental de 'время' (temps) : 'Со ...'", options: ["временем", "время", "времени"], correctAnswer: 0 },
                { question: "'Человек, который говорит по-русски' peut être remplacé par:", options: ["говорящий по-русски человек", "сказанный по-русски человек"], correctAnswer: 0 },
                { question: "Le verbe 'улететь' signifie:", options: ["arriver en volant", "partir en volant", "traverser en volant"], correctAnswer: 1 },
                { question: "Complétez : 'Летом я работал ... (un guide)'", options: ["гид", "гида", "гидом"], correctAnswer: 2 },
                { question: "Le participe passif passé 'построенный' vient du verbe...", options: ["строить (imperfectif)", "построить (perfectif)"], correctAnswer: 1 },
                { question: "Pour dire 'il s'est approché de la fenêtre', on dit 'он ... к окну'", options: ["отошёл", "подошёл", "перешёл"], correctAnswer: 1 },
                { question: "Instrumental de 'они' (ils) : 'Я иду с ...'", options: ["их", "им", "ними"], correctAnswer: 2 },
                { question: "'Мальчик, играющий в футбол' signifie:", options: ["Le garçon qui a joué au foot", "Le garçon qui joue au foot", "Le football joué par le garçon"], correctAnswer: 1 },
                { question: "Le verbe 'добежать' signifie :", options: ["commencer à courir", "partir en courant", "atteindre en courant"], correctAnswer: 2 },
                { question: "Complétez: 'Пахнет ... (le printemps)' - 'Ça sent le printemps'", options: ["весна", "весны", "весной"], correctAnswer: 2 },
                { question: "'Потерянные ключи' signifie:", options: ["les clés qui perdent", "les clés perdues", "les clés qui ont perdu"], correctAnswer: 1 },
                { question: "Pour 's'éloigner de la maison', on dit '... от дома'", options: ["подойти", "отойти", "войти"], correctAnswer: 1 },
                { question: "Instrumental de 'дочь' (fille) : 'Горжусь ...'", options: ["дочь", "дочерью", "дочери"], correctAnswer: 1 },
                { question: "'Фильм, который мы посмотрели' peut être remplacé par:", options: ["посмотренный нами фильм", "смотрящий нами фильм"], correctAnswer: 0 },
                { question: "Le verbe 'вбежать' signifie:", options: ["sortir en courant", "entrer en courant", "traverser en courant"], correctAnswer: 1 },
                { question: "Complétez : 'Она управляла ... (une grande entreprise)'", options: ["большая компания", "большой компанией", "большую компанию"], correctAnswer: 1 },
                { question: "'Любящая мать' signifie:", options: ["la mère aimée", "la mère qui aime", "la mère qui a aimé"], correctAnswer: 1 },
                { question: "Le verbe 'спуститься' signifie:", options: ["monter", "descendre", "entrer"], correctAnswer: 1 },
                { question: "Instrumental de 'лошадь' (cheval) : 'Ехать на ...'", options: ["лошади", "лошадью", "лошадь"], correctAnswer: 1 },
                { question: "'Письмо, полученное вчера' signifie:", options: ["La lettre qui a reçu hier", "La lettre reçue hier"], correctAnswer: 1 },
                { question: "Pour 'passer devant le magasin', on dit '... мимо магазина'", options: ["пройти", "перейти", "войти"], correctAnswer: 0 },
                { question: "Complétez : 'Я доволен ... (le résultat)'", options: ["результат", "результатом", "результата"], correctAnswer: 1 },
                { question: "'Улыбающийся ребёнок' signifie:", options: ["l'enfant qui sourit", "l'enfant souriant", "les deux sont corrects"], correctAnswer: 2 },
                { question: "Le verbe 'переехать' signifie:", options: ["arriver en transport", "déménager / traverser en transport", "partir en transport"], correctAnswer: 1 },
                { question: "Instrumental de 'Пушкин' : 'Роман, написанный ...'", options: ["Пушкин", "Пушкина", "Пушкиным"], correctAnswer: 2 },
                { question: "'Сломанный телефон' signifie:", options: ["le téléphone qui casse", "le téléphone cassé", "le téléphone qui a cassé"], correctAnswer: 1 },
                { question: "Pour 'se rassembler, se réunir', on utilise le verbe:", options: ["разойтись", "сойтись", "пройтись"], correctAnswer: 1 },
                { question: "Complétez : 'Он руководит ... (le projet)'", options: ["проект", "проекта", "проектом"], correctAnswer: 2 },
                { question: "Gérondif présent : '..., он слушал музыку.' (en travaillant)", options: ["Работая", "Поработав", "Работающий"], correctAnswer: 0 },
                { question: "Pour dire 'afin de', on utilise la construction...", options: ["потому что + phrase", "чтобы + infinitif", "если + phrase"], correctAnswer: 1 },
                { question: "Gérondif passé : '..., он пошёл домой.' (ayant terminé le travail)", options: ["Заканчивая работу", "Закончив работу", "Законченная работа"], correctAnswer: 1 },
                { question: "Quelle phrase est correcte ?", options: ["Я боюсь собаку", "Я боюсь собаки", "Я боюсь собакой"], correctAnswer: 1 },
                { question: "Le pronom 'свой' remplace 'мой', 'твой', 'его' etc. quand le possesseur est...", options: ["le complément du verbe", "le sujet du verbe", "n'importe qui"], correctAnswer: 1 },
                { question: "Complétez : 'Анна любит ... мужа.' (son propre mari)", options: ["её", "своего", "свой"], correctAnswer: 1 },
                { question: "Le conditionnel en russe s'exprime avec le passé du verbe et la particule...", options: ["бы", "ли", "же"], correctAnswer: 0 },
                { question: "Traduisez 'Si j'avais de l'argent, j'achèterais une voiture.'", options: ["Если у меня будут деньги, я куплю машину.", "Если бы у меня были деньги, я бы купил машину."], correctAnswer: 1 },
                { question: "Quelle est la forme courte de l'adjectif 'красивая'?", options: ["красиво", "красива", "красив"], correctAnswer: 1 },
                { question: "Le verbe 'заниматься' (s'occuper de) requiert quel cas?", options: ["Accusatif", "Génitif", "Instrumental"], correctAnswer: 2 },
                { question: "Complétez : 'Он занимается ...' (le sport).", options: ["спорт", "спорта", "спортом"], correctAnswer: 2 },
                { question: "Pour 'atteindre un but', on dit '... цели'.", options: ["достичь", "получить", "взять"], correctAnswer: 0 },
                { question: "Le verbe 'радоваться' (se réjouir de) requiert quel cas?", options: ["Datif", "Accusatif", "Génitif"], correctAnswer: 0 },
                { question: "Complétez : 'Она радуется ...' (le cadeau).", options: ["подарку", "подарок", "подарка"], correctAnswer: 0 },
                { question: "Le préfixe 'до-' dans les verbes de mouvement signifie souvent...", options: ["éloignement", "action jusqu'à un point", "action à travers"], correctAnswer: 1 }
            ], 
            vocabularyBank: [
                {ru: 'общество', fr: 'société'}, {ru: 'правительство', fr: 'gouvernement'}, {ru: 'закон', fr: 'loi'}, {ru: 'выборы', fr: 'élections'}, {ru: 'политика', fr: 'politique'}, {ru: 'экономика', fr: 'économie'}, {ru: 'культура', fr: 'culture'}, {ru: 'искусство', fr: 'art'}, {ru: 'наука', fr: 'science'}, {ru: 'образование', fr: 'éducation'}, {ru: 'здоровье', fr: 'santé'}, {ru: 'природа', fr: 'nature'}, {ru: 'окружающая среда', fr: 'environnement'}, {ru: 'проблема', fr: 'problème'}, {ru: 'решение', fr: 'solution/décision'}, {ru: 'возможность', fr: 'possibilité/opportunité'}, {ru: 'трудность', fr: 'difficulté'}, {ru: 'отношение', fr: 'relation/attitude'}, {ru: 'чувство', fr: 'sentiment'}, {ru: 'мысль', fr: 'pensée'}, {ru: 'мнение', fr: 'opinion'}, {ru: 'спор', fr: 'dispute/débat'}, {ru: 'согласие', fr: 'accord'}, {ru: 'причина', fr: 'cause/raison'}, {ru: 'следствие', fr: 'conséquence'}, {ru: 'развитие', fr: 'développement'}, {ru: 'рост', fr: 'croissance'}, {ru: 'успех', fr: 'succès'}, {ru: 'неудача', fr: 'échec'}, {ru: 'ошибка', fr: 'erreur'}, {ru: 'знание', fr: 'connaissance'}, {ru: 'умение', fr: 'compétence'}, {ru: 'навык', fr: 'savoir-faire'}, {ru: 'привычка', fr: 'habitude'}, {ru: 'характер', fr: 'caractère'}, {ru: 'поведение', fr: 'comportement'}, {ru: 'сравнение', fr: 'comparaison'}, {ru: 'разница', fr: 'différence'}, {ru: 'качество', fr: 'qualité'}, {ru: 'количество', fr: 'quantité'}, {ru: 'источник', fr: 'source'}, {ru: 'информация', fr: 'information'}, {ru: 'событие', fr: 'événement'}, {ru: 'новость', fr: 'nouvelle'}, {ru: 'статья', fr: 'article'}, {ru: 'доклад', fr: 'rapport/exposé'}, {ru: 'обсуждать/обсудить', fr: 'discuter de'}, {ru: 'критиковать', fr: 'critiquer'}, {ru: 'хвалить/похвалить', fr: 'louer/féliciter'}, {ru: 'утверждать', fr: 'affirmer'}, {ru: 'сомневаться', fr: 'douter'}, {ru: 'предполагать/предположить', fr: 'supposer'}, {ru: 'доказывать/доказать', fr: 'prouver'}, {ru: 'влиять/повлиять (на)', fr: 'influencer'}, {ru: 'зависеть (от)', fr: 'dépendre de'}, {ru: 'создавать/создать', fr: 'créer'}, {ru: 'уничтожать/уничтожить', fr: 'détruire'}, {ru: 'защищать/защитить', fr: 'protéger'}, {ru: 'участвовать (в)', fr: 'participer (à)'}, {ru: 'организовывать/организовать', fr: 'organiser'}, {ru: 'управлять', fr: 'gérer/diriger'}, {ru: 'руководить', fr: 'diriger (des gens)'}, {ru: 'сотрудничать', fr: 'collaborer'}, {ru: 'достигать/достичь', fr: 'atteindre'}, {ru: 'предпочитать/предпочесть', fr: 'préférer'}, {ru: 'сравнивать/сравнить', fr: 'comparer'}, {ru: 'требовать/потребовать', fr: 'exiger'}, {ru: 'существовать', fr: 'exister'}, {ru: 'оборудование', fr: 'équipement'}, {ru: 'исследование', fr: 'recherche'}, {ru: 'преимущество', fr: 'avantage'}, {ru: 'недостаток', fr: 'inconvénient'}, {ru: 'уверенность', fr: 'certitude'}, {ru: 'надежда', fr: 'espoir'}, {ru: 'цель', fr: 'objectif/but'}, {ru: 'задача', fr: 'tâche/problème'}, {ru: 'граница', fr: 'frontière'}, {ru: 'правило', fr: 'règle'}, {ru: 'ощущение', fr: 'sensation'}, {ru: 'память', fr: 'mémoire'}, {ru: 'внимание', fr: 'attention'}, {ru: 'бояться', fr: 'avoir peur'}, {ru: 'гордиться', fr: 'être fier de'}, {ru: 'наслаждаться', fr: 'profiter de / savourer'}, {ru: 'жаловаться/пожаловаться', fr: 'se plaindre'}
            ],
            sentenceBank: [
                { ru: 'Книга, написанная этим автором, стала бестселлером.', fr: 'Le livre écrit par cet auteur est devenu un best-seller.' },
                { ru: 'Работая над проектом, он слушал музыку.', fr: 'En travaillant sur le projet, il écoutait de la musique.' },
                { ru: 'Если бы я знал, я бы тебе сказал.', fr: 'Si j\'avais su, je te l\'aurais dit.' },
                { ru: 'Он вошёл в комнату, не сказав ни слова.', fr: 'Il est entré dans la pièce sans dire un mot.' },
                { ru: 'Она гордится своими детьми.', fr: 'Elle est fière de ses enfants.' },
                { ru: 'Мы должны перейти улицу на зелёный свет.', fr: 'Nous devons traverser la rue au feu vert.' },
                { ru: 'Закончив работу, мы пошли домой.', fr: 'Ayant terminé le travail, nous sommes rentrés à la maison.' },
                { ru: 'Чтобы выучить язык, нужно много практиковаться.', fr: 'Pour apprendre une langue, il faut beaucoup pratiquer.' }
            ]
        },
        { 
            id: "C1", 
            title: "Niveau C1 - Avancé", 
            description: "Expressions idiomatiques, nuances sémantiques et structures syntaxiques complexes.", 
            quizQuestions: [
                { question: "Que signifie l'expression 'водить за нос'?", options: ["Travailler dur", "Mener en bateau", "Avoir de la chance"], correctAnswer: 1 },
                { question: "Gérondif imperfectif : '..., я слушал музыку.' (En rentrant à la maison)", options: ["Возвращаясь домой", "Вернувшись домой"], correctAnswer: 0 },
                { question: "Pour souhaiter 'bonne chance' avant un examen, un Russe dira:", options: ["Сломай ногу!", "Ни пуха ни пера!", "Удачи!"], correctAnswer: 1 },
                { question: "Gérondif perfectif : '..., он сразу лёг спать.' (Étant arrivé)", options: ["Приехав", "Приезжая"], correctAnswer: 0 },
                { question: "L'expression 'делать из мухи слона' signifie:", options: ["Faire d'une mouche un éléphant (exagérer)", "Résoudre un problème", "Ignorer un problème"], correctAnswer: 0 },
                { question: "Pour demander à emprunter un objet ('Puis-je avoir un stylo?'), on utilise:", options: ["попросить ручку", "спросить ручку"], correctAnswer: 0 },
                { question: "Traduisez 'Il marchait dans la rue en parlant au téléphone'.", options: ["Он шёл по улице, говоря по телефону.", "Он шёл по улице, сказав по телефону."], correctAnswer: 0 },
                { question: "Que répond-on traditionnellement à 'Ни пуха ни пера!'?", options: ["Спасибо!", "К чёрту!", "Пожалуйста!"], correctAnswer: 1 },
                { question: "'Ayant fini le travail, nous sommes allés au cinéma'.", options: ["Заканчивая работу...", "Закончив работу..."], correctAnswer: 1 },
                { question: "Que veut dire 'у него денег куры не клюют'?", options: ["Il est pauvre", "Il est très riche", "Il aime les poules"], correctAnswer: 1 },
                { question: "Si vous voulez demander une information ('Où est la gare?'), vous allez...", options: ["попросить, где вокзал", "спросить, где вокзал"], correctAnswer: 1 },
                { question: "Le gérondif imperfectif (ex: 'читая') décrit une action...", options: ["simultanée à l'action principale", "antérieure à l'action principale"], correctAnswer: 0 },
                { question: "'Когда рак на горе свистнет' est l'équivalent de:", options: ["Demain matin", "Quand les poules auront des dents", "Il y a longtemps"], correctAnswer: 1 },
                { question: "Le gérondif perfectif (ex: 'сделав') décrit une action...", options: ["simultanée à l'action principale", "antérieure à l'action principale"], correctAnswer: 1 },
                { question: "Pour rapporter une parole ('Il a dit qu'il viendrait'), on préfère...", options: ["Он говорил...", "Он сказал..."], correctAnswer: 1 },
                { question: "L'expression 'зарубить себе на носу' signifie:", options: ["Se blesser", "Bien retenir quelque chose", "Ne rien comprendre"], correctAnswer: 1 },
                { question: "Choisissez le gérondif correct : 'Он слушал музыку, ... домашнее задание.'", options: ["делая", "сделав"], correctAnswer: 0 },
                { question: "Que signifie 'сидеть сложа руки'?", options: ["Être assis confortablement", "Ne rien faire, se tourner les pouces", "Méditer"], correctAnswer: 1 },
                { question: "Pour dire 'Mettre un chapeau (sur soi)', on dit '... шляпу'.", options: ["Одеть", "Надеть"], correctAnswer: 1 },
                { question: "Gérondif du verbe 'улыбнуться' (sourire, perfectif) :", options: ["Улыбаясь", "Улыбнувшись"], correctAnswer: 1 },
                { question: "L'expression 'быть не в своей тарелке' veut dire:", options: ["ne pas être dans son assiette", "avoir très faim", "être très en colère"], correctAnswer: 0 },
                { question: "Traduisez : 'N'ayant pas compris la question, il s'est tu.'", options: ["Не понимая вопрос, он молчал.", "Не поняв вопрос, он замолчал."], correctAnswer: 1 },
                { question: "Que signifie 'обвести вокруг пальца'?", options: ["Porter une bague", "Faire une promesse", "Tromper, duper quelqu'un"], correctAnswer: 2 },
                { question: "Pour dire 'J'habille mon enfant', on dit 'Я ... ребёнка'.", options: ["одеваю", "надеваю"], correctAnswer: 0 },
                { question: "Gérondif de 'возвращаться' (revenir, imperfectif) :", options: ["Возвращаясь", "Вернувшись"], correctAnswer: 0 },
                { question: "L'expression 'как дважды два четыре' signifie:", options: ["C'est très difficile", "C'est une opinion", "C'est simple comme bonjour"], correctAnswer: 2 },
                { question: "Quelle phrase est grammaticalement correcte ?", options: ["Читая книгу, мне стало интересно.", "Когда я читал книгу, мне стало интересно."], correctAnswer: 1 },
                { question: "Que signifie 'точить лясы'?", options: ["Aiguiser des couteaux", "Bavarder pour ne rien dire", "Manger avec appétit"], correctAnswer: 1 },
                { question: "Le verbe 'являться' (être, formel) est souvent suivi par quel cas?", options: ["Nominatif", "Instrumental", "Accusatif"], correctAnswer: 1 },
                { question: "Gérondif de 'увидеть' (apercevoir, perfectif) :", options: ["Видя", "Увидев"], correctAnswer: 1 },
                { question: "L'expression 'медвежья услуга' signifie:", options: ["un très grand service", "un service qui cause plus de tort que de bien", "un service rendu par une personne forte"], correctAnswer: 1 },
                { question: "Choisissez la phrase correcte :", options: ["Он ушёл, не прощаясь.", "Он ушёл, не попрощавшись."], correctAnswer: 1 },
                { question: "Que signifie 'знать как свои пять пальцев'?", options: ["Ne rien savoir", "Connaître très mal", "Connaître sur le bout des doigts"], correctAnswer: 2 },
                { question: "Le mot 'супруг' est une version plus formelle de:", options: ["брат (frère)", "друг (ami)", "муж (mari)"], correctAnswer: 2 },
                { question: "Gérondif de 'думать' (penser, imperfectif) :", options: ["Думая", "Подумав"], correctAnswer: 0 },
                { question: "Que signifie l'expression 'во весь голос'?", options: ["En chuchotant", "À tue-tête", "Avec une belle voix"], correctAnswer: 1 },
                { question: "Choisissez la phrase correcte :", options: ["Позавтракав, я ушёл на работу.", "Завтракая, я ушёл на работу."], correctAnswer: 0 },
                { question: "L'expression 'бить баклуши' signifie:", options: ["Ne rien faire, paresser", "Frapper quelqu'un", "Jouer d'un instrument"], correctAnswer: 0 },
                { question: "Le verbe 'отсутствовать' signifie:", options: ["être présent", "être absent", "participer"], correctAnswer: 1 },
                { question: "Gérondif de 'прочитать' (lire en entier, perfectif) :", options: ["Читая", "Прочитав"], correctAnswer: 1 },
                { question: "Que signifie 'выйти из себя'?", options: ["Sortir de chez soi", "Sortir de ses gonds", "Devenir sobre"], correctAnswer: 1 },
                { question: "Différence entre 'слушать' et 'слышать'?", options: ["Aucune", "'слушать' (écouter, volontaire) vs 'слышать' (entendre, perception)", "'слушать' (formel) vs 'слышать' (informel)"], correctAnswer: 1 },
                { question: "Gérondif de 'жить' (vivre, imperfectif) :", options: ["Живя", "Пожив"], correctAnswer: 0 },
                { question: "L'expression 'сломя голову' signifie:", options: ["Très lentement", "Avec une migraine", "À toute vitesse"], correctAnswer: 2 },
                { question: "Le verbe 'предоставить' est plus formel que...", options: ["дать (donner)", "взять (prendre)", "купить (acheter)"], correctAnswer: 0 },
                { question: "Gérondif de 'понять' (comprendre, perfectif) :", options: ["Понимая", "Поняв"], correctAnswer: 1 },
                { question: "Que signifie 'зайти в тупик'?", options: ["Entrer dans une ruelle", "Se retrouver dans une impasse", "Aller au bout de son idée"], correctAnswer: 1 },
                { question: "Différence entre 'смотреть' et 'видеть'?", options: ["Aucune", "'смотреть' (regarder, action) vs 'видеть' (voir, perception)", "'смотреть' (rapide) vs 'видеть' (long)"], correctAnswer: 1 },
                { question: "L'expression 'спустя рукава' signifie:", options: ["Avec beaucoup de soin", "De manière négligente, par-dessus la jambe", "En ayant froid aux mains"], correctAnswer: 1 },
                { question: "La particule 'же' sert souvent à...", options: ["Exprimer le doute", "Renforcer une question ou une opposition", "Indiquer le futur"], correctAnswer: 1 },
                { question: "Que signifie l'expression 'рукой подать'?", options: ["Donner la main", "C'est juste à côté", "C'est très loin"], correctAnswer: 1 },
                { question: "Le verbe 'осуществлять' est une version formelle de...", options: ["делать (faire)", "начинать (commencer)", "видеть (voir)"], correctAnswer: 0 },
                { question: "L'expression 'засучив рукава' est le contraire de 'спустя рукава' et signifie:", options: ["Paresser", "En retroussant ses manches (avec zèle)", "Se laver les mains"], correctAnswer: 1 },
                { question: "Pour indiquer une cause de manière formelle, on peut utiliser 'поскольку', qui signifie:", options: ["malgré", "cependant", "puisque / étant donné que"], correctAnswer: 2 },
                { question: "Le mot 'быт' fait référence à...", options: ["l'être philosophique", "la vie quotidienne, le train-train", "un ancien conte"], correctAnswer: 1 },
                { question: "Traduisez la nuance : 'Он хороший врач.' vs 'Он хороший как врач.'", options: ["Aucune différence", "Le 1er: il est bon. Le 2nd: il est bon en tant que médecin.", "Le 1er est formel, le 2nd informel"], correctAnswer: 1 },
                { question: "Que signifie 'обращаться с кем-либо'?", options: ["Se tourner vers quelqu'un", "S'adresser à quelqu'un", "Traiter quelqu'un / se comporter avec"], correctAnswer: 2 },
                { question: "La structure 'несмотря на то, что...' signifie :", options: ["parce que...", "afin que...", "malgré le fait que..."], correctAnswer: 2 },
                { question: "L'expression 'камень преткновения' signifie :", options: ["une pierre précieuse", "la pierre d'achoppement", "une fondation solide"], correctAnswer: 1 },
                { question: "Le verbe 'подразумевать' signifie :", options: ["comprendre", "penser", "sous-entendre"], correctAnswer: 2 },
                { question: "Que signifie l'expression 'играть первую скрипку'?", options: ["Savoir jouer du violon", "Jouer un rôle de premier plan", "Être débutant"], correctAnswer: 1 },
                { question: "Quelle est la différence entre 'наконец' et 'в конце концов'?", options: ["Aucune", "'наконец' (enfin, après attente) vs 'в конце концов' (finalement, en conclusion)", "Le premier est un lieu, le second un temps"], correctAnswer: 1 },
                { question: "Le verbe 'способствовать' (contribuer à) requiert quel cas?", options: ["Accusatif", "Génitif", "Datif"], correctAnswer: 2 },
                { question: "Que signifie 'семи пядей во лбу'?", options: ["Avoir un grand front", "Être très intelligent", "Être têtu"], correctAnswer: 1 },
                { question: "Le mot 'мировоззрение' se traduit par...", options: ["Vue sur le monde (paysage)", "Vision du monde (philosophie)", "Tour du monde"], correctAnswer: 1 }
            ],
            vocabularyBank: [
                {ru: 'справедливость', fr: 'justice'}, {ru: 'свобода', fr: 'liberté'}, {ru: 'ответственность', fr: 'responsabilité'}, {ru: 'совесть', fr: 'conscience (morale)'}, {ru: 'сознание', fr: 'conscience (état)'}, {ru: 'власть', fr: 'pouvoir'}, {ru: 'государство', fr: 'état (pays)'}, {ru: 'гражданин', fr: 'citoyen'}, {ru: 'человечество', fr: 'humanité'}, {ru: 'судьба', fr: 'destin'}, {ru: 'душа', fr: 'âme'}, {ru: 'разум', fr: 'raison/intellect'}, {ru: 'сомнение', fr: 'doute'}, {ru: 'уверенность', fr: 'certitude'}, {ru: 'надежда', fr: 'espoir'}, {ru: 'отчаяние', fr: 'désespoir'}, {ru: 'вдохновение', fr: 'inspiration'}, {ru: 'творчество', fr: 'créativité'}, {ru: 'произведение', fr: 'œuvre'}, {ru: 'достижение', fr: 'accomplissement'}, {ru: 'преимущество', fr: 'avantage'}, {ru: 'недостаток', fr: 'inconvénient'}, {ru: 'впечатление', fr: 'impression'}, {ru: 'воспоминание', fr: 'souvenir'}, {ru: 'представление', fr: 'idée/concept'}, {ru: 'точка зрения', fr: 'point de vue'}, {ru: 'мировоззрение', fr: 'vision du monde'}, {ru: 'конфликт', fr: 'conflit'}, {ru: 'переговоры', fr: 'négociations'}, {ru: 'соглашение', fr: 'accord'}, {ru: 'договор', fr: 'contrat'}, {ru: 'условие', fr: 'condition'}, {ru: 'требование', fr: 'exigence'}, {ru: 'предложение', fr: 'proposition/phrase'}, {ru: 'вывод', fr: 'conclusion'}, {ru: 'доказательство', fr: 'preuve'}, {ru: 'факт', fr: 'fait'}, {ru: 'явление', fr: 'phénomène'}, {ru: 'процесс', fr: 'processus'}, {ru: 'система', fr: 'système'}, {ru: 'структура', fr: 'structure'}, {ru: 'элемент', fr: 'élément'}, {ru: 'особенность', fr: 'particularité'}, {ru: 'характеристика', fr: 'caractéristique'}, {ru: 'функция', fr: 'fonction'}, {ru: 'анализ', fr: 'analyse'}, {ru: 'синтез', fr: 'synthèse'}, {ru: 'метод', fr: 'méthode'}, {ru: 'подход', fr: 'approche'}, {ru: 'принцип', fr: 'principe'}, {ru: 'теория', fr: 'théorie'}, {ru: 'практика', fr: 'pratique'}, {ru: 'открытие', fr: 'découverte'}, {ru: 'изобретение', fr: 'invention'}, {ru: 'технология', fr: 'technologie'}, {ru: 'современный', fr: 'moderne/contemporain'}, {ru: 'древний', fr: 'ancien'}, {ru: 'уникальный', fr: 'unique'}, {ru: 'типичный', fr: 'typique'}, {ru: 'необходимый', fr: 'indispensable'}, {ru: 'достаточный', fr: 'suffisant'}, {ru: 'чрезмерный', fr: 'excessif'}, {ru: 'осознавать/осознать', fr: 'prendre conscience de'}, {ru: 'преодолевать/преодолеть', fr: 'surmonter'}, {ru: 'способствовать', fr: 'contribuer à'}, {ru: 'препятствовать', fr: 'faire obstacle à'}, {ru: 'наследие', fr: 'héritage'}, {ru: 'современник', fr: 'contemporain (personne)'}, {ru: 'бытие', fr: 'l\'être/existence'}, {ru: 'сущность', fr: 'essence'}, {ru: 'предназначение', fr: 'vocation/destinée'}, {ru: 'последствие', fr: 'conséquence'}, {ru: 'взаимодействие', fr: 'interaction'}, {ru: 'противоречие', fr: 'contradiction'}, {ru: 'обосновывать/обосновать', fr: 'justifier/fonder'}, {ru: 'трактовать', fr: 'interpréter'}, {ru: 'свидетельствовать', fr: 'témoigner'}, {ru: 'заключаться в', fr: 'consister en'}, {ru: 'отличаться от', fr: 'se distinguer de'}, {ru: 'стремиться к', fr: 'aspirer à'}, {ru: 'жертвовать', fr: 'sacrifier'}, {ru: 'воспринимать/воспринять', fr: 'percevoir'}, {ru: 'осуществлять/осуществить', fr: 'réaliser/effectuer'}, {ru: 'убеждать/убедить', fr: 'convaincre'}, {ru: 'разочарование', fr: 'déception'}, {ru: 'сострадание', fr: 'compassion'}, {ru: 'равнодушие', fr: 'indifférence'}, {ru: 'лицемерие', fr: 'hypocrisie'}
            ],
            sentenceBank: [
                { ru: 'Он водил меня за нос целую неделю.', fr: 'Il m\'a mené en bateau pendant toute une semaine.' },
                { ru: 'Несмотря на плохую погоду, мы решили пойти гулять.', fr: 'Malgré le mauvais temps, nous avons décidé d\'aller nous promener.' },
                { ru: 'Он знает этот город как свои пять пальцев.', fr: 'Il connaît cette ville comme sa poche.' },
                { ru: 'Пришлось работать засучив рукава, чтобы закончить в срок.', fr: 'Il a fallu travailler d\'arrache-pied pour finir dans les délais.' },
                { ru: 'Этот вопрос является камнем преткновения в наших переговорах.', fr: 'Cette question est la pierre d\'achoppement dans nos négociations.' },
                { ru: 'Он вышел из себя, когда услышал новости.', fr: 'Il est sorti de ses gonds quand il a appris la nouvelle.' },
                { ru: 'Говорить на эту тему — всё равно что делать из мухи слона.', fr: 'Parler de ce sujet, c\'est comme faire d\'une mouche un éléphant.' },
                { ru: 'Поскольку времени было мало, мы сразу перешли к делу.', fr: 'Comme nous avions peu de temps, nous sommes allés droit au but.' }
            ]
        }
    ]
};

// On exporte la variable pour la rendre accessible à d'autres fichiers
export { contentData };